Dispute Framework 2.0
filecoin-project/notary-governance pull request #876
Opened 2023-05-05 21:15 UTC by raghavrmadya

2023-05-05 21:32 UTC, galen-mcandrew commented on README.md
> +- Responder is notified by the T&T WG Lead and allowed to submit additional details in the T&T WG slack or present at the T&T WG Call.
Add link to T&T Working Group Slack channel.
Add link to T&T WG Call Calendar (similar to Notary gov call calendar: https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles

2023-05-05 21:35 UTC, galen-mcandrew commented on README.md
> +Once a dispute is filed, the T&T WG Lead will discuss it in the WG calls. The average time for a dispute to be resolved is two weeks based on the principles of optimistic governance but some disputes
Add period

2023-05-05 21:44 UTC, galen-mcandrew commented on README.md
> +- A violation of the agreed-upon [operating guidelines](https://github.com/filecoin-project/notary-governance/blob/main/notaries#operational-guidelines), or some other act of impropriety.
remove period

2023-05-05 21:44 UTC, galen-mcandrew commented on README.md
> +- Being asked to step away from the Fil+ community.
remove period

2023-05-05 21:45 UTC, galen-mcandrew commented on README.md
> +Claimants are discouraged from making personal attacks against any stakeholder when submitting details in the T&T dispute tracker anbd follow the [Fil+ Code of Conduct](https://medium.com/filecoin-pl
typo, correct **anbd** to and

2023-05-05 21:47 UTC, galen-mcandrew requested changes
Added some inline comments, mostly just formatting

2023-05-08 16:11 UTC, merged

2023-05-08 16:16 UTC, raghavrmadya reviewed
thanks for the review!